### PR TITLE
#155 Remove /api

### LINKED ISSUE #155: Remove /api from API address
The current API address is `api.codequiz.local/api/v1/`
Change the address to be `api.codequiz.local/v1` by removing the `/api`

### PR DESCRIPTION
**Pull request by metinbaris**
-Fixes #155

### CODE REVIEW

**Review by pfwd — CHANGES_REQUESTED** [review]
Looks great but could you please merge the latest changes from `main` as I have fixed an issue with the API-Client GitHub workflow which _should_ fix the checks in your PR.

**Comment by metinbaris** [comment]
@pfwd Thanks for the update, seems it is now blowed up with questions 🤣

**Comment by metinbaris** [comment]
> @pfwd Thanks for the update, seems it is now blowed up with questions 🤣

@pfwd any advice on this point, I should move on somewhere else if this part is stopped

**Comment by pfwd** [comment]
Hey @metinbaris Sorry for the late reply.  I've been away.

I spent the evening working on your branch.  It turns out that it was an issue with the routing.  See https://github.com/howToCodeWell/code-quiz/pull/158/commits/a06fbb80c3fcc6109da1638be5e169549322e0cb I also updated the ports to `8080` in https://github.com/howToCodeWell/code-quiz/pull/158/commits/7d75941561c86742518685e1c0491b2ee98d9d78

The tests are all passing now so I will merge it in.  Thanks for your help on this one

**Review by pfwd — APPROVED** [review]
LGTM

**Pull request merged**
